name: helper_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ElanDeyan/helper_tools

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  analyzer: ^6.3.0
  lint: ^2.2.0
  test: ^1.24.0
